const data = [
    {   id: 0,
        name: "Water",
        price: 1,
        volume: 100000,
    },
    {   id: 1,
        name: "Milk",
        price: 2,
        volume: 80000,
    },
    {   id: 2,
        name: "Chocolate milk",
        price: 3.6,
        volume: 20000,
    },
    {   id: 3,
        name: "Tea",
        price: 1.4,
        volume: 75000,
    },
    {   id: 4,
        name: "Coffee",
        price: 4.2,
        volume: 61500,
    },
    {   id: 5,
        name: "Hot chocolate",
        price: 4,
        volume: 14900,
    },
    {   id: 6,
        name: "Apple juice",
        price: 1.8,
        volume: 50000,
    },
    {   id: 7,
        name: "Orange juice",
        price: 2.2,
        volume: 32000,
    },
    {   id: 8,
        name: "Pineapple Juice",
        price: 2.8,
        volume: 6520,
    },
    {   id: 9,
        name: "Beer",
        price: 1.25,
        volume: 85000,
    },
    {   id: 10,
        name: "Wine",
        price: 12.2,
        volume: 11200,
    },
    {   id: 11,
        name: "Vodka",
        price: 9.9,
        volume: 950,
    },

];

module.exports = {
    get: function(id) {
        return data[id];
    },
    list: function() {
        return data;
    }
}