<template>
  <div v-on:click="shake" id="magic8ball" class="column is-one-third-tablet"
    :class="{'shake-horizontal': animated}" @animationend="animated = false">
    <h1>Click to shake the Magic 8-ball!</h1>
    <div id="output">{{ output }}</div>
  </div>
</template>

<script>
export default {
  name: 'Box9-8ball',

  data() {
    return{
      result: [
        "It is certain.",
        "It is decidedly so.",
        "Without a doubt.",
        "Yes - definitely.",
        "You may rely on it.",
        "As I see it, yes.",
        "Most likely.",
        "Outlook good.",
        "Yes.",
        "Signs point to yes.",
        "Reply hazy, try again.",
        "Ask again later.",
        "Better not tell you now.",
        "Cannot predict now.",
        "Concentrate and ask again.",
        "Don't count on it.",
        "My reply is no.",
        "My sources say no.",
        "Outlook not so good.",
        "Very doubtful."
      ],
      output: "Click me to shake!",
      img8ball: "",
      animated: false,
    };
  },

  mounted() { //Load images
    this.img8ball = require("../assets/magic8ball.png");
  },

  methods: {
    shake: function() { //Generate random number 0-19, output result
      this.animated = true;
      for(var i = 0; (i*100) < 1500 ; i++) {
        setTimeout( () => { this.output = this.result[ Math.floor(Math.random()*20) ]} , (i*100) );
      }
    }
  },
};
</script>

<style scoped>
h1 {
  color: #14ffec;
}

#magic8ball {
  background-image: url("../assets/magic8ball.png");
  background-repeat: no-repeat;
  background-position: center;
  background-size: 60%;
}

#output {
  width: 25%;
  margin: auto;
  padding-top: 8vh;
  color: #0d7377;
  font-size: 0.9em;
  font-weight: bold;
}

.column {
  background-color: #323232;
  border-color: #212121;
}

.shake-horizontal {
	-webkit-animation: shake-horizontal 1500ms ease-out both;
	animation: shake-horizontal 1500ms ease-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-1-24 14:31:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation shake-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
            transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
            transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
}

@keyframes shake-horizontal {
  0%,
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
  }
  10%,
  30%,
  50%,
  70% {
    -webkit-transform: translateX(-10px);
            transform: translateX(-10px);
  }
  20%,
  40%,
  60% {
    -webkit-transform: translateX(10px);
            transform: translateX(10px);
  }
  80% {
    -webkit-transform: translateX(8px);
            transform: translateX(8px);
  }
  90% {
    -webkit-transform: translateX(-8px);
            transform: translateX(-8px);
  }
}
</style>
